"""empty message

Revision ID: 1aa96d9f6269
Revises: 1bdc70eeb068
Create Date: 2023-04-05 18:04:30.107069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1aa96d9f6269'
down_revision = '1bdc70eeb068'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_credentials', sa.Column('imap_server', sa.String(length=120), nullable=True))
    op.add_column('email_credentials', sa.Column('pop_port', sa.Integer(), nullable=True))
    op.add_column('email_credentials', sa.Column('imap_port', sa.Integer(), nullable=True))
    op.add_column('email_credentials', sa.Column('smtp_port', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('email_credentials', 'smtp_port')
    op.drop_column('email_credentials', 'imap_port')
    op.drop_column('email_credentials', 'pop_port')
    op.drop_column('email_credentials', 'imap_server')
    # ### end Alembic commands ###
