"""empty message

Revision ID: 1bdc70eeb068
Revises: 2660e38c2364
Create Date: 2023-04-05 16:24:34.394284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bdc70eeb068'
down_revision = '2660e38c2364'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('email_credentials', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('email_credentials', 'pop_server',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.alter_column('email_credentials', 'smtp_server',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('email_credentials', 'smtp_server',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.alter_column('email_credentials', 'pop_server',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.alter_column('email_credentials', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
