"""mongo

Revision ID: 330c8c0882fe
Revises: 6fbc01be4cb2
Create Date: 2023-04-10 23:56:20.555666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '330c8c0882fe'
down_revision = '6fbc01be4cb2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
