"""email_support

Revision ID: 6fbc01be4cb2
Revises: 1aa96d9f6269
Create Date: 2023-04-05 18:16:57.069904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fbc01be4cb2'
down_revision = '1aa96d9f6269'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
